name: CI Load Test Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Setup Kubernetes Cluster
        run: |
          chmod +x scripts/cluster-setup.sh
          ./scripts/cluster-setup.sh

