name: CI Load Test Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Setup Kubernetes Cluster
        run: |
          chmod +x script/cluster-setup.sh
          ./script/cluster-setup.sh


      - name: Install Ingress Controller
        run: |
          chmod +x script/install-ingress.sh
          ./script/install-ingress.sh


      - name: Deploy Applications
        run: |
          chmod +x script/deploy-apps.sh
          ./script/deploy-apps.sh


      - name: Deploy Ingress Rules
        run: |
          chmod +x script/deploy-ingress.sh
          ./script/deploy-ingress.sh



